Maybe use of Debian image would be better because lighter ?
plexinc/pms-docker pull request #68
Opened 2021-10-12 14:49 UTC by tigerblue77

Just an idea...
Don't hesitate to tell me if I'm wrong and why. Also, I removed "unrar" package as it is not available on default Debian repositories ; if it was necessary (I didn't see where) but "tar" command could be use without needing any package installation.

2021-12-08 09:10 UTC, zbyte-king approved these changes

2022-10-20 10:33 UTC, Re4zOon commented
Hi,

Just a quick question: Why are you using apt-get instead of apt?
Is it just preference, or?
I dont see the reason to use the old/outdated apt-get anymore, specially on fresh distros.

2022-10-20 10:37 UTC, tigerblue77 commented
> Hi,
> 
> Just a quick question: Why are you using apt-get instead of apt? Is it just preference, or? I dont see the reason to use the old/outdated apt-get anymore, specially on fresh distros.

Hello,
"old/outdated `apt-get`" ? Sorry but I think you're wrong. `apt` is using `apt-get` and is just the recommended command for interactive use by administrators, not for use in shell scripts. That's why, when you use `apt` in a bash script you get the following message :
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

2022-10-20 10:42 UTC, Re4zOon commented
Sorry, you are right. I never really looked into the differences and whatnot.

2023-02-16 18:18 UTC, Randyblo7 requested changes
Nice

2025-07-24 19:20 UTC, cilindrox commented
Closing this as unplanned for now.

2025-07-24 19:20 UTC, closed without merging